include $(PROJ_ROOT)/make_pre.mk

RADAR_PRINCIPLES_LIB_NAME = radar_principles
RADAR_PRINCIPLES_LIB_SRCS = burn_through_range.c doppler_frequency.c power_aperture.c pulse_train.c radar_range_equation.c range_resolution.c sdjpn.c self_screening_jammer.c stand_off_jammer.c
#TARGET_SRCS = main.c snr_dr_rcs.c

include $(PROJ_ROOT)/make_post.mk
